spring:
  application:
    name: Simudaq-api

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
#        show_sql: true
#    show-sql: true

kis:
  app-key: ${APP_KEY}
  app-secret: ${APP_SECRET}
  domain:
    url: https://openapi.koreainvestment.com:9443
  websocket:
    url: ws://ops.koreainvestment.com:21000  # KIS WebSocket 서버 URL
    max-reconnect-attempts: 10  # 최대 재연결 시도 횟수
    reconnect-delay: 3000  # 재연결 대기 시간 (ms)
  path:
    chart-min-today: /uapi/domestic-stock/v1/quotations/inquire-time-itemchartprice
    chart-min-past: /uapi/domestic-stock/v1/quotations/inquire-time-dailychartprice
    chart-period: /uapi/domestic-stock/v1/quotations/inquire-daily-itemchartprice


# WebSocket STOMP 엔드포인트 설정
websocket:
  endpoints:
    stock-data-topic: /topic/stock/  # 실시간 주식 시세 데이터 브로드캐스트 토픽

springdoc:
  packages-to-scan: com.simudap.controller
  api-docs:
    path: /docs
    groups.enabled: false
  swagger-ui:
    path: /docs/ui
    display-operation-id: true
    syntax-highlight.theme: monokai
    doc-expansion: none
